name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Ensure dist folder exists
        run: ls -la dist/  # Debugging step

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: deployment-assets
          path: dist/  # Ensure build output exists here
          retention-days: 3  # Increase retention

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-assets
          path: dist/

      - name: Verify downloaded files
        run: ls -la dist/  # Debugging step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./dist
          keep_files: false
